config/routes.rb
Rails.application.routes.draw do

  resources :cats, only: [:index, :show, :create, :edit, :new, :update]
  get 'cats/:cat_id/cat_rental_requests', to: 'cat_rental_requests#index'
  resources :cat_rental_requests, only: [:new, :create, :show] do
    member do
      patch 'deny'
      patch 'approve'
    end
  end

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  CAT_COLORS = %w{red black white purple}

  validates :birth_date, :name, :sex, presence: true
  validates :color, inclusion: { in: CAT_COLORS,
    message: "%{value} is not a valid color" }
  validates :sex, inclusion: { in: %w{F M},
      message: "%{value} is not a valid sex" }

  has_many :cat_rental_requests, dependent: :destroy

  def age
    (Date.today - self.birth_date)/365.to_f
  end

  
end

app/models/cat_rental_request.rb
require 'byebug'

class CatRentalRequest < ActiveRecord::Base
  REQUEST_STATES = %w{PENDING APPROVED DENIED}
  validates :cat_id, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: REQUEST_STATES,
    message: "%{value} is not a valid request state" }
  validate :overlapping_approved_requests

  belongs_to :cat,
    class_name: :Cat,
    foreign_key: :cat_id,
    primary_key: :id

  def ordered_dates
    if self.start_date > self.end_date
      self.errors[:start_date] << "must be before end date"
      return false
    end
    true
  end

  def overlapping_requests
    self.class.where(
      "end_date > ? AND start_date < ?", self.start_date, self.end_date
    ).where(cat_id: self.cat_id).where.not(id: self.id)
  end

  def overlapping_approved_requests
    return true unless self.status == "APPROVED"
    overlap = overlapping_requests
    approved = overlap.where(status:"APPROVED")
    unless approved.empty?
      self.errors[:cat_id] << "is already booked during that period"
      return false
    end
    true
  end

  def approve!
    begin
      ActiveRecord::Base.transaction do
        self.update!(status: "APPROVED")
        overlapping_requests.each(&:deny!)
      end
    rescue ActiveRecord::RecordInvalid => arri
      return false
    end
    true
  end

  def deny!
    self.update!(status: "DENIED")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def index
    cat = Cat.find(params[:cat_id])
    @cat_rental_requests = cat.cat_rental_requests
    render json: @cat_rental_requests
  end

  def new
    @cats = Cat.all
  end

  def create
    cr = CatRentalRequest.new(cat_rental_requests_parameters)
    if cr.save
      redirect_to cat_url
    else
      render status: :unprocessable_entity
    end
  end

  def show
    @crr = CatRentalRequest.find(params[:id])
    if @crr.nil?
      render status: :not_found
    else
      # render json: @cat
    end
  end

  def approve
    crr = CatRentalRequest.find(params[:id])
    crr.approve!
    redirect_to :back
  end

  def deny
    crr = CatRentalRequest.find(params[:id])
    crr.deny!
    redirect_to :back
  end

  private

  def cat_rental_requests_parameters
    params.require(:cat_rental_request).permit(:cat_id,:start_date,:end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    # render json: @cats
  end

  def show
    @cat = Cat.find(params[:id])
    @rental_requests = @cat.cat_rental_requests.order(:start_date)
    if @cat.nil?
      render status: :not_found
    else
      # render json: @cat
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.nil?
      render status: :not_found
    else
      if @cat.update(cat_parameters)
        redirect_to cat_url(@cat.id)
      else
        render status: :unprocessable_entity
      end
    end
  end

  def create
    cr = Cat.new(cat_parameters)
    if cr.save
      redirect_to cats_url
    else
      render status: :unprocessable_entity
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    if @cat.nil?
      render status: :not_found
    else
      #pass
    end
  end

  def new
    @cat = Cat.new
  end

  private

  def cat_parameters
    params.require(:cat).permit(:color, :name, :birth_date, :sex, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/_form.html.erb
<html>
  <body>
    <form action=<%= cat_rental_requests_url %> method="POST">
      <label for="cat select">Select a cat: </label>
      <select id="cat select" name="cat_rental_request[cat_id]">
        <% cats.each do |cat| %>
          <option value=<%= cat.id %> ><%= cat.name %></option>
        <% end %>
      </select>
      <label for="start date">Pick a start date: </label>
      <input type="date" name="cat_rental_request[start_date]" value=<%= Date.today %>>

      <label for="end date">Pick an end date: </label>
      <input type="date" name="cat_rental_request[end_date]" value=<%= Date.tomorrow %>>

      <input type="submit" value="book it">
    </form>
  </body>
</html>

app/views/cat_rental_requests/new.html.erb
<%= render "form", cat: @cat %>

app/views/cat_rental_requests/show.html.erb
<html>
  <body>

  </body>
</html>

app/views/cats/_form.html.erb
<% action = cat.persisted? ? "patch" : "post" %>
<% action_url = (action == "post") ? cats_url : cat_url(id: cat.id) %>

  <form action=<%= action_url %> method="post" >
    <input type="hidden" name="_method" value=<%= action %>>
    <label for="name">Name: </label>
    <input type="text" id="name" name=cat[name]
      value=<%= cat.name %> ></input>
    <br/>

    <label for="sex">Sex: </label>
    <input type="radio" id="name" name=cat[sex] value="F"
      <%= cat.sex == "F" ? "checked=\"checked\"" : "" %> >Female</input>
    <input type="radio" id="name" name=cat[sex] value="M"
      <%= cat.sex == "M" ? "checked=\"checked\"" : "" %> >Male</input>
    <br/>

    <label for="color">Color:</label>
    <select id="color" name="cat[color]">
      <option disabled="true" selected="true" value="tie-dye">Select a color</option>
      <option value="red"
        <%= cat.color == "red" ? "selected=\"selected\"" : "" %> >Red</option>
      <option value="white"
        <%= cat.color == "white" ? "selected=\"selected\"" : "" %>>White</option>
      <option value="black"
        <%= cat.color == "black" ? "selected=\"selected\"" : "" %>>Black</option>
      <option value="purple"
        <%= cat.color == "purple" ? "selected=\"selected\"" : "" %> >Purple</option>
    </select>
    <br/>

    <label for="dob">Date of Birth:</label>
    <input type='date' id="dob" name=cat[birth_date]
      value=<%= cat.birth_date || Date.today %> >
    <br/>

    <label>Warm and Fuzzy Memories <br/>
      <textarea name="cat[description]" cols="30" rows="10"
      ><%= cat.description %></textarea>
    </label>

    <br/>
    <input type="submit" value="Submit">
  </form>

  </body>
</html>

app/views/cats/edit.html.erb
<%= render "form", cat: @cat %>

app/views/cats/index.html.erb
<html>
<body>
  <ul>
    <% @cats.each do |cat| %>
      <li><a href=<%= cat_url(cat.id) %>>
        <%= cat.name %>
      </a></li>
    <% end %>
  </ul>
</body>
</html>

app/views/cats/new.html.erb
<%= render "form", cat: @cat %>

app/views/cats/show.html.erb
<html>
  <body>
    <h2>Kittinfo</h2>
    <%= render "shared/object", obj: @cat %>
    <h2>Rental Requests</h2>
    <% @rental_requests.each do |rental| %>
      <%= render "shared/object", obj: rental  %>
      <% if rental.status == "PENDING" %>
        <%= button_to "Approve", approve_cat_rental_request_url(rental.id),
              method: :patch %>
        <%= button_to "Deny", deny_cat_rental_request_url(rental.id),
              method: :patch %>
      <% end %>
      <br/>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_object.html.erb
<table border="2px">

  <tr>
    <% obj.attributes.keys.each do |col| %>
      <th> <%= col %> </th>
    <% end %>
  </tr>
  <tr>
    <% obj.attributes.values.each do |val| %>
      <td> <%= val %> </td>
    <% end %>
  </tr>
</table>